artifact_location: file:///Users/fernandohernandezesquivel/Documents/MLops_Project/mlflow_runs/353615530630397546
creation_time: 1781990467867
experiment_id: '353615530630397546'
last_update_time: 1781990467867
lifecycle_stage: active
name: NVIDIA_Price_Prediction
