artifact_location: file:///Users/fernandohernandezesquivel/Documents/MLops_Project/mlflow_runs/504246946478130849
creation_time: 1782078802236
experiment_id: '504246946478130849'
last_update_time: 1782078802236
lifecycle_stage: active
name: NVIDIA_Price_Predictor
