aliases: []
creation_timestamp: 1782070322392
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1782070322392
metrics: null
model_id: m-76c1f1c434134e39b43b4c8114800203
name: NVIDIA_Price_Predictor
params: null
run_id: 1567d29ac2c44ecf8ea7ed4c9a1707d5
run_link: null
source: models:/m-76c1f1c434134e39b43b4c8114800203
status: READY
status_message: null
storage_location: file:///Users/fernandohernandezesquivel/Documents/MLops_Project/mlflow_runs/353615530630397546/models/m-76c1f1c434134e39b43b4c8114800203/artifacts
user_id: null
version: 2
